name = "JuliaLeetCode"
uuid = "1a985e11-4546-46c0-893d-247f3bf315cf"
authors = ["Chayan Datta"]
version = "1.0.0-DEV"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
